### ISSUE TITLE
ช่วยเพิ่มลิสต์จากนี้ได้ไหมครับ?

### ISSUE THREAD

**Issue by maxjame5432** [easylist-thailand/easylist-thailand#1]
สวัสดีครับ

คือพอดีผมทำลิสต์เป็นของตัวเองอยู่ครับ เลยอยากแบ่งปัน ไม่รู้ว่ามันถูก Format ของตัว uBlock หรือป่าวเพราะลองบล็อกไปแล้วตัว uBlock กลับบล็อกที่อยูในลิสต์ไม่ได้ แต่พอเป็น Adblock plus กลับบล็อกเลย ลองพิจารณาเพิ่มจาก[ไฟล์ที่ให้โหลดนี้](https://od.lk/d/MF8xMTM3MTgzNTBf/adsth.txt)ได้นะครับ

**Comment by gluons** [comment]
รบกวนแบ่งประเภทให้หน่อยได้ไหมครับ จะได้จัดการง่ายกว่านี้ครับ 🙃

**Comment by maxjame5432** [comment]
ได้ครับ เดียวผมขอเวลาสักพักนะครับ ถ้าเสร็จแล้วผมอีเมลกลับครับ

ดาวน์โหลด Outlook for Android<https://aka.ms/ghei36>



On Sat, Apr 15, 2017 at 12:56 PM +0700, "Saran Tanpituckpong" <notifications@github.com<mailto:notifications@github.com>> wrote:


รบกวนแบ่งประเภทให้หน่อยได้ไหมครับ จะได้จัดการง่ายกว่านี้ครับ 🙃

**Comment by maxjame5432** [comment]
เรียบร้อยครับ มีแก้เยอะครับ เพราะบางอันบล็อกแต่รูปจึงเป็นลิงค์รูปแทนเลยกลับไปบล็อกใหม่อีกครั้งครับ

https://od.lk/d/MF8xNDYxODQ0ODdf/List.txt

**Comment by gluons** [comment]
โอเคครับ เดี๋ยวผมจะนำมาเพิ่มเข้าด้วยกันให้ครับ

แต่พอดีผมวางแผนจะปรับ code ตัว gen ใหม่ อาจช้านิดนึงต้องขออภัยไว้ล่วงหน้านะครับ 😖

**Comment by gluons** [comment]
@maxjame5432 ผมใส่ให้แล้วนะครับ

**Comment by maxjame5432** [comment]
ขอบคุณครับ เดียวถ้ามีเพิ่มเติมเดียวผมจะตั้ง Issue ใหม่ครับ แต่มีอีกเว็บนึงที่ผมบล็อกไม่ถูกเพราะบล็อกทีมันจะโดน navigator ของเว็บครับคือ "จีจี-anime" ครับ จะบล็อกแต่ภาพก็กลัวจะกลับมาอีก

**Comment by gluons** [comment]
โอเคครับ เดี๋ยวผมมาดูให้

**Comment by gluons** [comment]
@maxjame5432 `gg-anime` แก้ไขให้แล้วนะครับ
