### ISSUE TITLE
Use Date & Time as version

### ISSUE THREAD

**Issue by gluons** [easylist-thailand/easylist-thailand#10]
**Date & Time** is more suitable for filter list version than Semver.  
Because it frequently updates. 🤔

We should use **Date & Time**, like `yyyyMMddHHmm`, instead of Semver.

---

**วัน-เวลา** น่าจะเหมาะสมกับพวกรายการตัวกรองมากกว่า Semver
เพราะว่ามันมีการอัพเดทที่ถี่กว่า

เราควรจะใช้รูปแบบ**วัน-เวลา** เช่น `yyyyMMddHHmm` แทน Semver

**Comment by gluons** [comment]
@kowith337 ใน [Release](https://github.com/easylist-thailand/easylist-thailand/releases) น่าจะไม่ได้ใส่แล้วครับ เพราะถ้ามีการอัพเดทบ่อยหรือเยอะคงจะใส่กันไม่ไหว 😨

อย่าง [Release](https://github.com/easylist/easylist/releases) ของ [easylist](https://github.com/easylist/easylist) เองเขาก็ไม่ได้เขียน เพราะมันเยอะมากจริงๆ และไม่มีความจำเป็นเลยครับ  
เพราะจริงๆแล้ว filter list **ไม่ใช่ software** คนใช้ไม่ได้อยากรู้ว่าเราเพิ่มลบแก้ไขอะไรไป เขาอยากรู้แค่ว่ามันใช้ได้ 🤔

จริงๆแล้วผมก็พลาดเอง ตอนแรกดันติดนิสัยใส่เวอร์ชั่นแบบ Semver 😅

**Comment by gluons** [comment]
@kowith337 มีความเห็นว่าไงก็บอกเล่ากันได้นะครับ

**Comment by kowith337** [comment]
ก็ตามนั้นแหละครับ เอาจริงก็ไม่ต้องทำ Release ก็ได้ อาศัยแค่มันดึง Raw File มา แล้วมันจะอัพเดทของมันเอง ถ้าเลยเวลา Expire ที่เราตั้ง...
พูดถึง `Expire` ถ้าเราอัพเดทกันบ่อยๆ ถี่ๆ เซ็ทไว้ 30 วันมันยาวไปครับ ปรับให้เหลือแค่อาทิตย์เดียวก็ยังดี...

**Comment by gluons** [comment]
ตอนนี้ `Expires` ผมตั้งไว้ 3 วันอ่ะครับ

https://github.com/easylist-thailand/easylist-thailand/blob/83ffc7bf8ec727405a73c6da2da7e47bdf548077/assets/header.txt#L1-L7
