### ISSUE TITLE
Separate uBlock specific filters to isolated file.

### ISSUE THREAD

**Issue by gluons** [easylist-thailand/easylist-thailand#28]
**From:** https://github.com/easylist-thailand/easylist-thailand/commit/1fff46d304b7533508a7982703dfaaf1aac13c6f#commitcomment-37567041

Separate uBlock specific filters to isolated file.  
Include it with `!#include [file name]` and `!#if ext_ublock` [pre-parsing directives](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#pre-parsing-directives) from uBlock.

**Comment by krystian3w** [comment]
File no longer need condition if base have.

https://github.com/easylist-thailand/easylist-thailand/blob/f117ddaf6befd02f357ef48c456fe6d5382d94ce/categories/ublock.txt#L1 https://github.com/easylist-thailand/easylist-thailand/blob/f117ddaf6befd02f357ef48c456fe6d5382d94ce/categories/ublock.txt#L122

**Comment by gluons** [comment]
Done in 715b2a0d1998abe6781f0164a0e7488494fbd2bc.
