### ISSUE TITLE
PDPA

### ISSUE THREAD

**Issue by mishari** [easylist-thailand/easylist-thailand#34]
ผมอยากเสนอหมวดหมู่ใหม่สำหรับ PDPA notice ทั้งหลายครับ (เช่น: เว็บไซต์นี้ใช้คุกกี้...) คิดว่าเหมาะสมไหม?

**Comment by gluons** [comment]
รายละเอียดเป็นยังไงหรอครับ? ต้องการจะ block พวก หน้าต่างข้อความเตือน รึเปล่าครับ? หรือต้องการ block แบบไหนหรอครับ?

**Comment by kowith337** [comment]
เข้าใจว่าเป็น Notice Bar ที่แจ้งการใช้คุกกี้ของ Browser ครับ คล้ายๆ กับ GDPR ของอังกฤษ

**Comment by mishari** [comment]
ใช่ครับ ยกตัวอย่างจากเว็บมติชนครับ
https://www.matichon.co.th/news-monitor/news_2272162
![image](https://user-images.githubusercontent.com/503018/87870587-b169ba00-c9d3-11ea-8c79-12f5f547579d.png)
ตอนนี้ผมเอาไปลงใน https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_annoyance_international.txt อยู่ครับ

**Comment by gluons** [comment]
โอเคครับ  
คิดว่าผมอาจจะเพิ่มใส่ในหมวด annoyance นะครับ

**Comment by mishari** [comment]
ขอบคุณครับ

**Comment by kowith337** [comment]
ผม List เฉพาะเว็บทั้งหมดในเครือของมติชนที่แสดงแถบ PDPA ก่อนนะครับ จากหน้า https://www.matichon.co.th/privacy-policy

อันนี้บล็อกแค่ DOM แถบข้างล่าง
`khaosod.co.th,khaosodenglish.com,matichon.co.th,matichonacademy.com,matichonbook.com,matichonelibrary.com,matichonweekly.com,prachachat.net,sentangsedtee.com,silpa-mag.com,technologychaoban.com###pdpa-popup`

แต่ถ้า Block Path ของ Wordpress Plugin เลย มันจะไม่โชว์...
`/plugin-pdpa/$domain=khaosod.co.th|khaosodenglish.com|matichon.co.th|matichonacademy.com|matichonbook.com|matichonelibrary.com|matichonweekly.com|prachachat.net|sentangsedtee.com|silpa-mag.com|technologychaoban.com`
