### ISSUE TITLE
movie2uhd.com

### ISSUE THREAD

**Issue by T-H-O-R** [easylist-thailand/easylist-thailand#36]
![ใหม่2020](https://user-images.githubusercontent.com/63744737/98506114-667af780-228d-11eb-920f-d623e9b235d1.jpg)

**Comment by ouoam** [comment]
ผมนั่งแกะโค้ดเขาเล่นดู เลยได้ออกมาเป็นอย่างนี้ หลังจากลองหลายวิธี
`hdd.movies-store.com##+js(json-prune, MU_ads)`
ผมใช้ uBlock origin นะครับ

**Comment by T-H-O-R** [comment]
hdd.movies-store.com##+js(json-prune, MU_ads) ใช้ได้จริงด้วยขอบคุณมากๆเลย

> ผมนั่งแกะโค้ดเขาเล่นดู เลยได้ออกมาเป็นอย่างนี้ หลังจากลองหลายวิธี
> `hdd.movies-store.com##+js(json-prune, MU_ads)`
> ผมใช้ uBlock origin นะครับ
