### ISSUE TITLE
Bad bad rule added on 7/1/21

### ISSUE THREAD

**Issue by ysrn** [easylist-thailand/easylist-thailand#44]
Someone added:
`
||*d*.com/*.gif$image
`
To categories/movie.txt.

This obviously blocks ALL gifs from ANY site that happens to have the letter "d" in it. 
I don't see how this silly rule could have gotten approved and merged?!

**Comment by gluons** [comment]
My mistake.

#42

**Comment by tonzsm** [comment]
Sorry
