### ISSUE TITLE
Blocking cxense.com in tn.com.ar breaks functionality

### ISSUE THREAD

**Issue by rndmUsr678** [easylist-thailand/easylist-thailand#66]
if you visit an article in the website, for example this one: https://tn.com.ar/deportes/futbol/2021/11/14/oscar-lopez-turitich-el-heroe-olvidado-perdio-la-pierna-a-causa-de-la-diabetes-y-hoy-lo-mantienen-sus-excompaneros-de-river/, at the bottom of the page, the images are broken, due to the rules that block _cxense.com_

Screenshot showing the broken images:

![Screen Shot 2021-11-14 at 07 29 27](https://user-images.githubusercontent.com/94295285/141680439-b26f9b6e-c952-4ff0-8da8-a1518a040510.png)

**Comment by kowith337** [comment]
It's not Thai website, this filter intent to apply to Thai sites and Thai users, `cxense.com` are actually tracking and it seems good to be blocked because I see it's commonly use on local news site and some portals, e.g. MThai, Sanook, etc.

**Comment by rndmUsr678** [comment]
I see. How about making an exception for this particular website (tn.com.ar) and only for this particular script cdn.cxense.com/cx.js That would fix the broken website while still protecting users from tracking
