### ISSUE TITLE
hanimesubth.com [NSFW]

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist-thailand/easylist-thailand#69]
Ad images on `https://hanimesubth.com/`

<details>
<summary> screenshot </summary>
<img width="604" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/157764725-84b23380-ed55-4778-823b-709accb88be3.PNG">

</details>

Browser: firefox
Adblocker: uBlock Origin 1.41.8
Filterlists: uBlock Origin default + THA: EasyList Thailand

**Comment by gluons** [comment]
Many ads can be blocked by main [EasyList](https://github.com/easylist/easylist) rules.  
So, I'll block some ads that doesn't covered by main EasyList.
