### ISSUE TITLE
ต่อเนื่องจาก #7

### ISSUE THREAD

**Issue by kowith337** [easylist-thailand/easylist-thailand#8]
ตอนนี้ผมกำลังลองแยกตัวกรองที่ผมทำ (ThaiParanoidBlock) มาใส่ตามหมวดหมู่ที่แบ่งไว้แล้วครับ ทว่าตอนนี้ยังไม่เสร็จดี
แต่พอดีว่าตัวกรองใน `categories` มีเคาะวรรคเยอะ เลยลองเรียงดูใหม่ (ใช้ Notepad++) แล้วค่อย Generate ทีเดียว (ตอนนี้ยังไม่ได้ทำ Pull เพราะมันเพิ่ม-ลดบรรทัดเยอะจัด ถ้ากลัวว่าโค้ดมันเปลี่ยนเยอะเกินก็ดูใน Fork ของผมก่อน แล้วค่อยตัดสินใจก็ได้ครับ)
> - มีก็แอบแก้อันไหนที่มี `www` นำหน้า ก็ลบส่วนที่นำหน้าออก เพราะมันจะได้มีผลทั้งเว็บ รวมถึง Subdomain นั้นๆ
> - ส่วนที่เป็นการบล็อกสคริปต์หรือรูปภาพที่เป็นโฆษณา (Requests) ผมแก้ไขและเติม `||` นำหน้าไว้ให้ จะได้บล็อกทั้ง Subdomain นั้นๆ เช่นกัน

อาจจะมีเพิ่ม Category นิดนึง ตอนนี้จะมี
- `hosts`: รวมโดเมนที่เป็นโฆษณาและ Tracking โดยเฉพาะ (แต่กลัวจะซ้ำซ้อน อาจจะย้ายไปใส่ใน `script` แทน)
- `tech`: เว็บที่รีวิวหรือบอกสเป็คของสินค้าไอที เช่น มือถือ โน้ตบุค ฯลฯ
- `ublock`: ตัวแปรบางตัวจะมีผลกับแค่ uBlock เท่านั้น เช่น การใช้เงื่อนไข `:has()`, `:not()`, หรือการฉีด Script `:script-inject()` เพื่อแก้ปัญหาบางอย่าง เช่น Anti-AdBlock

เพิ่มเติมนิดนึง ทีแรกติดรงที่ว่าตอนลง Ruby แล้วจะ Generate แล้วมันติดตรงที่สั่ง `bundle install` ไม่ได้ครับ ต้องสั่ง `install bundler` ก่อน ถึงจะคียคำสั่ง `bundle install` ได้
> กรณีที่ยังไม่ได้ลง `bundler` ก่อน มันจะฟ้องว่า `(LoadError)` ครับ แต่ถ้าลงไว้แล้วก็ใส่คำสั่งได้เลย

**Comment by gluons** [comment]
ผมกำลัง​คิด​อยู่​ว่า​อาจ​จะ​เขียน​ตัว​ generate ด้วย​ภาษา​อื่น​ ซึ่ง​อาจ​จะ​สะดวก​สำหรับ​คน​อื่น​ด้วย​ ตอนนี้​ก็​ใส่​แต่​ filter ใน​ text อย่าง​เดียว​ก็​ได้​ครับ​ เดี๋ยว​ผม​ gen ให้เอง 😅

**Comment by kowith337** [comment]
หะหะ ตอนนี้ทำเป็นแล้วครับ แต่ก็อย่างที่บอก โค้ดของผมเปลี่ยนจากโค้ดต้นทางไปเยอะ เลยให้ช่วยพิจารณาหน่อย

**Comment by kowith337** [comment]
หะหะ พูดไม่ค่อยถูกเท่าไหร่ครับ

**Comment by kowith337** [comment]
ตอนนี้กลายเป็นว่า Generate ไม่ผ่านครับ เข้าใจว่าเงื่อนไขของ uBlock (ที่ใส่ `:has()`, `not:()` มันไปทำอะไรสักอย่างที่ให้ตัว Gen มัน Gen ไม่ได้ เลยลบออกไปก่อน ค่อย Generate ใหม่ แบบไม่มี uBlock rules
```batch
** Execute generate
rake aborted!
ArgumentError: malformed format string - %"
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/lib/easylist_generator.rb:16:in `format'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/lib/easylist_generator.rb:16:in `head'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/Rakefile:15:in `block in <top (required)>'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
C:/tools/ruby25/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
C:/tools/ruby25/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
C:/Users/*****/Documents/GitHub/easylist-thailand_fork/vendor/bundle/ruby/2.5.0/bin/rake:23:in `<main>'
Tasks: TOP => default => generate
```

ส่วนอันนี้ลอง Gen เองดู
https://github.com/kowith337/easylist-thailand/blob/711a8d8ac1ce26a820973e0ab200fffebcf659e7/subscription/easylist-thailand.txt

**Comment by gluons** [comment]
แก้ไขเรียบร้อยแล้วครับ ลอง gen ดูได้ครับ

**Comment by kowith337** [comment]
รอบนี้โอเคแล้วครับ พึ่งกลับไปเช็คใหม่ มันติดที่ตรงนี้นี่เอง (ฮา)
`kapook.com##body > div[style*="width:100%"]:has(div[style*="z-index:888"])`

**Comment by gluons** [comment]
@kowith337 ตอนนี้ผมเพิ่ม Travis CI ให้ช่วย build แล้วนะครับ ไม่ต้องมานั่ง gen เองอีกต่อไป  
แค่ commit ไฟล์ txt ขึ้นไปก็พอครับ เดี๋ยว @traviscibot ทำให้ครับ
